### PR TITLE
fix: start sampling heap profiler before any asynchronous calls

### LINKED ISSUE #160: Heap Profiles are missing Module stacks
Profiles taken with [sampling-heap-profiler](https://github.com/v8/sampling-heap-profiler/issues/16) have stacks which contain functions like `Module.runMain` and `Module._load`, like the following profile from ofrobots collected in https://github.com/v8/sampling-heap-profiler/issues/16:
image

cloud-profiler-nodejs does not collect with stacks with functions like `Module.runMain` or `Module._load`. 

This is likely because the [`start()`](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/86ef3ab605aea7a8d5d0750aef3224a6f7f8162d/ts/src/index.ts#L124) function for cloud-profiler-nodejs is asynchronous, so we can't collect samples on the first tick.

Right now, [`start()`](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/86ef3ab605aea7a8d5d0750aef3224a6f7f8162d/ts/src/index.ts#L124) must be asynchronous because [`initConfig()`](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/86ef3ab605aea7a8d5d0750aef3224a6f7f8162d/ts/src/index.ts#L55) is asynchronous, so it can retrieve instance and zone from metadata when those fields are not passed in.

### PR DESCRIPTION
**Pull request by nolanmar511**
fixes #160

### CODE REVIEW

File: ts/src/index.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ import {Profiler} from './profiler';
 
 const common: Common = require('@google-cloud/common');
 const pjson = require('../../package.json');
+const heapProfiler = require('bindings')('sampling_heap_profiler');
```
Comment (aalexand) [inline ts/src/index.ts]: It doesn't seem right to call directly into the binding here. The profilers/heap-profiler should be the only level of abstraction on top of that, so call that.

BTW, heap-profiler still calls enable() from its constructor? Doesn't seem right if so - not sure which effects calling that twice has.

File: ts/src/index.ts [hunk 2]
```diff
@@ -129,13 +130,28 @@ export async function start(config: Config = {}): Promise<void> {
...
+    heapProfiler.startSamplingHeapProfiler(
+        config.heapIntervalBytes || defaultConfig.heapIntervalBytes,
+        config.heapMaxStackDepth || defaultConfig.heapIntervalBytes);
+  }
+
   let normalizedConfig: ProfilerConfig;
   try {
     normalizedConfig = await initConfig(config);
   } catch (e) {
+    heapProfiler.stopSamplingHeapProfiler();
```
Comment (aalexand) [inline ts/src/index.ts]: Is it right that it's unconditional?

File: ts/src/index.ts [hunk 3]
```diff
@@ -152,7 +168,21 @@ function logError(msg: string, config: Config) {
  * profiles.
  */
 export async function startLocal(config: Config = {}): Promise<void> {
+  // start the v8 heap profiler if heap profiling is enabled. This must be done
+  // before any asynchronous calls are made so samples from the first tick can
+  // be captured.
+  if (!(config.disableHeap === false)) {
```
Comment (aalexand) [inline ts/src/index.ts]: Can it be just `if (!!config.disableHeap)`?

File: ts/src/index.ts [hunk 4]
```diff
@@ -129,13 +130,28 @@ export async function start(config: Config = {}): Promise<void> {
...
   try {
     normalizedConfig = await initConfig(config);
   } catch (e) {
+    heapProfiler.stopSamplingHeapProfiler();
     logError(`Could not start profiler: ${e}`, config);
     return;
   }
+
+  if (normalizedConfig.disableHeap) {
+    heapProfiler.stopSamplingHeapProfiler();
```
Comment (aalexand) [inline ts/src/index.ts]: Why is it stopped here? If this is sequence like "enable - disable - enable in the constructor" then it's pretty convoluted, any chance to simplify?

File: ts/src/index.ts (hunk 2 above)
Comment (aalexand) [inline ts/src/index.ts]: I think you want it in finally{}, not in catch{}. Then you can have it just once.

File: ts/src/index.ts (hunk 1 above)
Comment (nolanmar511) [reply ts/src/index.ts]: I've switched to creating a HeapProfiler, which is passed in to the profiler.

File: ts/src/index.ts (hunk 2 above)
Comment (nolanmar511) [reply ts/src/index.ts]: This is now conditional.

File: ts/src/index.ts (hunk 3 above)
Comment (nolanmar511) [reply ts/src/index.ts]: Done.

File: ts/src/index.ts (hunk 4 above)
Comment (nolanmar511) [reply ts/src/index.ts]: I think I've simplified this.

File: ts/src/index.ts [hunk 5]
```diff
@@ -129,14 +130,36 @@ export async function start(config: Config = {}): Promise<void> {
         config);
     return;
   }
+
+  // start the heap profiler if profiler config does not indicate heap profiling
+  // is disabled. This must be done before any asynchronous calls are made so
+  // samples from the first tick can be captured.
+  let heapProfiler: HeapProfiler|undefined;
+  if (!!config.disableHeap) {
```
Comment (ofrobots) [inline ts/src/index.ts]: Should this be a single negation?

File: ts/src/index.ts [hunk 6]
```diff
@@ -152,9 +175,22 @@ function logError(msg: string, config: Config) {
  * profiles.
  */
 export async function startLocal(config: Config = {}): Promise<void> {
+  // start the v8 heap profiler if heap profiling is enabled. This must be done
+  // before any asynchronous calls are made so samples from the first tick can
+  // be captured.
+  let heapProfiler: HeapProfiler|undefined;
+  if (!!config.disableHeap) {
```
Comment (ofrobots) [inline ts/src/index.ts]: ditto

**Comment by nolanmar511** [comment]
Sorry -- pushed to this branch by mistake at some point. 
The branch is now correct. PTAL

File: ts/src/index.ts [hunk 7]
```diff
@@ -129,14 +130,36 @@ export async function start(config: Config = {}): Promise<void> {
         config);
     return;
   }
+
+  // start the heap profiler if profiler config does not indicate heap profiling
```
Comment (aalexand) [inline ts/src/index.ts]: Nit: start -> Start

File: ts/src/index.ts [hunk 8]
```diff
@@ -129,14 +130,36 @@ export async function start(config: Config = {}): Promise<void> {
...
+  // is disabled. This must be done before any asynchronous calls are made so
+  // samples from the first tick can be captured.
+  let heapProfiler: HeapProfiler|undefined;
+  if (!config.disableHeap) {
+    heapProfiler = new HeapProfiler(
```
Comment (aalexand) [inline ts/src/index.ts]: Creating the heap profiler seems overkill. Can you have enable() / disable() methods as static on the heap profiler class (or just as functions) instead and call those?

Comment (aalexand) [reply ts/src/index.ts]: Also make enable() / disable() set and check the global boolean flag for whether the heap profiler is enabled. Then you can call disable() without a check around it.

File: ts/src/index.ts (hunk 7 above)
Comment (nolanmar511) [reply ts/src/index.ts]: Done.

File: ts/src/index.ts (hunk 8 above)
Comment (nolanmar511) [reply ts/src/index.ts]: I removed the heap profiler class. I think doing this addresses this comments, an also makes sense because (unlike the time profiler) the heap profiler can only be collecting a profile with one set of parameters.

**Comment by nolanmar511** [comment]
PTAL

File: ts/src/index.ts [hunk 9]
```diff
@@ -129,13 +130,34 @@ export async function start(config: Config = {}): Promise<void> {
         config);
     return;
   }
+
+  // Start the heap profiler if profiler config does not indicate heap profiling
+  // is disabled. This must be done before any asynchronous calls are made so
+  // samples from the first tick can be captured.
+  if (!config.disableHeap) {
+    heapProfiler.set(
```
Comment (aalexand) [inline ts/src/index.ts]: Requesting some changes:
* Remove set() method, pass parameters to enable().
* Rename enable() -> start(), disable() -> stop().
* Make stop() no op if start() wasn't called. Document it so. Remove isEnabled() method and just call stop() when needed.

This all should simplify code.

File: ts/src/index.ts [hunk 10]
```diff
@@ -129,13 +130,34 @@ export async function start(config: Config = {}): Promise<void> {
         config);
     return;
   }
+
+  // Start the heap profiler if profiler config does not indicate heap profiling
+  // is disabled. This must be done before any asynchronous calls are made so
+  // samples from the first tick can be captured.
```
[the remark this answers is not in the document]
Comment (aalexand) [reply ts/src/index.ts]: I think the requirement about the first tick is too strict. What I'd expect is that the heap profiling starts as soon as the require / start is called in the source and everything that is executed after / below that is heap-profiled.

[the remark this answers is not in the document]
Comment (nolanmar511) [reply ts/src/index.ts]: I clarified this comment. All code/allocations after .start() is called should be profiled.

File: ts/src/index.ts [hunk 11]
```diff
@@ -129,13 +130,31 @@ export async function start(config: Config = {}): Promise<void> {
...
   let normalizedConfig: ProfilerConfig;
   try {
     normalizedConfig = await initConfig(config);
   } catch (e) {
+    heapProfiler.stop();
     logError(`Could not start profiler: ${e}`, config);
     return;
   }
+
+  // stop heap profiler if, after initialization, the config indicates that
```
Comment (aalexand) [inline ts/src/index.ts]: Nit: stop -> Stop

File: ts/src/index.ts [hunk 12]
```diff
@@ -152,9 +171,24 @@ function logError(msg: string, config: Config) {
  * profiles.
  */
 export async function startLocal(config: Config = {}): Promise<void> {
+  // Start the v8 heap profiler if heap profiling is enabled. This must be done
```
Comment (aalexand) [inline ts/src/index.ts]: It feels that code from here up to "profiler = new Profiler(normalizedConfig);" could be shared between start() and startLocal()?

File: ts/src/profilers/heap-profiler.ts [hunk 13]
```diff
@@ -15,41 +15,54 @@
...
-   */
-  profile(): perftools.profiles.IProfile {
-    if (!this.enabled) {
-      throw new Error('Heap profiler is not enabled.');
-    }
-    const result = profiler.getAllocationProfile();
-    const startTimeNanos = Date.now() * 1000 * 1000;
-    return serializeHeapProfile(result, startTimeNanos, this.intervalBytes);
+/**
+ * Starts heap profiling. If heap profiling has already been started with
```
Comment (aalexand) [inline ts/src/profilers/heap-profiler.ts]: Optional: I think you could as well return an error if an attempt to start already started profiler with different parameters is made as I don't think it should ever be done with the current agent.

Comment (nolanmar511) [reply ts/src/profilers/heap-profiler.ts]: This is possible with the code as written.
If the user specifies heapIntervalBytes or heapMaxStackDepth in the config pointed to by GCLOUD_PROFILER_CONFIG, then [this](https://github.com/nolanmar511/cloud-profiler-nodejs/blob/193761afd9d42abd41e0b06dc2a175672657390a/ts/src/profiler.ts#L261-L262) line in startProfiler would start the profiler with different parameters... and the profiles could be off.

I can work around this, but only if we decide to never fix #116, because loading the config with require() makes it possible to load the config synchronously.

**Comment by aalexand** [comment]
Is this ready to be re-reviewed? Also, the coverage goes down, can tests be improved to make that go up or stay the same?

**Comment by nolanmar511** [comment]
I think I have one question which needs to be resolved before I make the changes to re-review this:

If the user specifies heapIntervalBytes or heapMaxStackDepth in the config pointed to by GCLOUD_PROFILER_CONFIG, then this line in startProfiler would start the profiler with different parameters... and the profiles could be off, or may end up missing allocations (I need to still investigate to determine the impact).

I can work around this, but only if we decide to not to fix #116, because loading the config with require() makes it possible to load the config synchronously.

I think loading the config with require is reasonable since [trace](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/c8c5bfc6168649cba65ca32cf53a524d38dac521/src/index.ts#L83-L84) still does this, and I'm guessing that, since trace needs to be started first, having an asynchronous piece of code when initializing the config would not work for trace.

**Comment by aalexand** [comment]
@nolanmar511 When we get rid of using `require`, could we use [readFileSync](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options) to read the config file contents? It's probably what `require` does underneath to be synchronous anyway.

**Comment by nolanmar511** [comment]
PTAL
I think planning to use readFileSync if a user specifies a config file is reasonable.

File: ts/src/index.ts [hunk 14]
```diff
@@ -90,23 +101,37 @@ export async function initConfig(config: Config): Promise<ProfilerConfig> {
...
+  return config;
 }
 
 let profiler: Profiler|undefined = undefined;
 
+/**
+ * Initializes the config, and starts heap profiler if the heap profiler is
+ * needed.
+ */
+export async function startHelper(config: Config): Promise<ProfilerConfig> {
```
Comment (aalexand) [inline ts/src/index.ts]: Would be good to name it more specifically than `startHelper`. Maybe `prepareStart` or `preStart` or even `initConfigAndMaybeStartHeapProfiler`?

File: ts/src/index.ts [hunk 15]
```diff
@@ -90,23 +101,37 @@ export async function initConfig(config: Config): Promise<ProfilerConfig> {
...
+  let profilerConfig = initConfig(config);
+
+  // Start the heap profiler if profiler config does not indicate heap profiling
+  // is disabled. This must be done before any asynchronous calls are made so
+  // all memory allocations made after start() is called can be captured.
+  if (!config.disableHeap) {
```
Comment (aalexand) [inline ts/src/index.ts]: Is this intentional that this checks config and not profilerConfig? If so, why it's not before the initConfig() call?

File: ts/src/profilers/heap-profiler.ts (hunk 13 above)
Comment (aalexand) [reply ts/src/profilers/heap-profiler.ts]: Should this return an error now if start() is called after the profiler is already started?

Comment (nolanmar511) [reply ts/src/profilers/heap-profiler.ts]: I think that makes sense.
Done.

File: ts/src/index.ts (hunk 14 above)
Comment (nolanmar511) [reply ts/src/index.ts]: I went with `initConfigAndMaybeStartHeapProfiler`.

File: ts/src/index.ts (hunk 15 above)
Comment (nolanmar511) [reply ts/src/index.ts]: Fixed.

**Comment by aalexand** [comment]
@nolanmar511 Ready to PTAL?

File: ts/src/index.ts (hunk 14 above)
Comment (aalexand) [reply ts/src/index.ts]: It doesn't look like the function is renamed? I'm still seeing startHelper.

File: ts/src/index.ts (hunk 15 above)
Comment (aalexand) [reply ts/src/index.ts]: Not fixed?

File: ts/src/profilers/heap-profiler.ts (hunk 13 above)
Comment (aalexand) [reply ts/src/profilers/heap-profiler.ts]: Not done?

File: ts/src/index.ts [hunk 16]
```diff
@@ -129,13 +155,21 @@ export async function start(config: Config = {}): Promise<void> {
...
-    normalizedConfig = await initConfig(config);
+    normalizedConfig = await initConfigAndMaybeStartHeapProfiler(config);
   } catch (e) {
     logError(`Could not start profiler: ${e}`, config);
     return;
   }
+
+  // Stop heap profiler if, after initialization, the config indicates that
+  // the heap profiler is disabled.
+  if (normalizedConfig.disableHeap) {
```
Comment (ofrobots) [inline ts/src/index.ts]: I don't think this case is possible any more, or is it? `disableHeap` can be synchronously configured only. `initConfigMetadata` cannot change the value of `disableHeap`.

Either remove, or change this to an assertion?

Comment (nolanmar511) [reply ts/src/index.ts]: Done.

Comment (nolanmar511) [reply ts/src/index.ts]: Done.

**Comment by nolanmar511** [comment]
PTAL

File: ts/src/index.ts [hunk 17]
```diff
@@ -129,13 +155,15 @@ export async function start(config: Config = {}): Promise<void> {
         config);
     return;
   }
+
   let normalizedConfig: ProfilerConfig;
```
Comment (aalexand) [inline ts/src/index.ts]: Looking more into it now, it feels you could move all of
```
let normalizedConfig: ProfilerConfig;
...
profiler = new Profiler(normalizedConfig);
```
into `initConfigAndMaybeStartHeapProfiler` naming it as createProfile() which returns the created profiler or null and call it as "profiler = createProfiler(); if (!profiler) return;" (the logging would be inside of createProfiler).

File: ts/src/index.ts [hunk 18]
```diff
@@ -129,13 +155,15 @@ export async function start(config: Config = {}): Promise<void> {
...
   try {
-    normalizedConfig = await initConfig(config);
+    normalizedConfig = await initConfigAndMaybeStartHeapProfiler(config);
   } catch (e) {
     logError(`Could not start profiler: ${e}`, config);
```
Comment (aalexand) [inline ts/src/index.ts]: start -> initialize?

File: ts/src/index.ts (hunk 17 above)
Comment (nolanmar511) [reply ts/src/index.ts]: Done.

File: ts/src/index.ts (hunk 18 above)
Comment (nolanmar511) [reply ts/src/index.ts]: Done.

**Comment by aalexand** [comment]
@nolanmar511 Did you push the changes? I don't see the "Done" things in the source.

**Comment by nolanmar511** [comment]
Haven't pushed the changes. Will add PTAL when I have.

**Comment by nolanmar511** [comment]
PTAL

**Comment by aalexand** [comment]
@ofrobots Could you LGTM as well?

File: ts/src/index.ts [hunk 19]
```diff
@@ -79,7 +78,20 @@ export async function initConfig(config: Config): Promise<ProfilerConfig> {
   const mergedConfig =
       extend(true, {}, defaultConfig, envSetConfig, envConfig, config);
 
-  if (!mergedConfig.zone || !mergedConfig.instance) {
+  if (!hasService(mergedConfig)) {
```
Comment (ofrobots) [inline ts/src/index.ts]: Q: does this change make this a semver major change? That is, previously working code may no longer work if it relied on the service context being discovered from the metadata service?

File: ts/src/index.ts [hunk 20]
```diff
@@ -90,22 +102,51 @@ export async function initConfig(config: Config): Promise<ProfilerConfig> {
...
+ * undefined.
+ */
+export async function createProfiler(config: Config):
+    Promise<Profiler|undefined> {
+  if (!semver.satisfies(process.version, pjson.engines.node)) {
+    logError(
+        `Could not start profiler: node version ${process.version}` +
+            ` does not satisfies "${pjson.engines.node}"`,
+        config);
+    return undefined;
```
Comment (ofrobots) [inline ts/src/index.ts]: nit: it would be better to throw here. This would get rid of the need to declare the return type to be the ungainly `Profiler|undefined`.

File: ts/src/index.ts [hunk 21]
```diff
@@ -90,22 +102,51 @@ export async function initConfig(config: Config): Promise<ProfilerConfig> {
...
   }
 
-  return mergedConfig;
-}
+  let profilerConfig: ProfilerConfig;
+  try {
+    profilerConfig = initConfigLocal(config);
+  } catch (e) {
+    logError(`Could not start profiler: ${e}`, config);
+    return undefined;
```
Comment (ofrobots) [inline ts/src/index.ts]: Likewise. Omit the catch block here, and let the throw reach the caller.

File: ts/src/index.ts [hunk 22]
```diff
@@ -122,21 +163,10 @@ let profiler: Profiler|undefined = undefined;
...
-        config);
-    return;
-  }
-  let normalizedConfig: ProfilerConfig;
-  try {
-    normalizedConfig = await initConfig(config);
-  } catch (e) {
-    logError(`Could not start profiler: ${e}`, config);
+  const profiler: Profiler|undefined = await createProfiler(config);
+  if (profiler === undefined) {
```
Comment (ofrobots) [inline ts/src/index.ts]: this test can be removed if you throw above. Omit the type for the local variable `profiler`.

File: ts/src/index.ts [hunk 23]
```diff
@@ -152,8 +182,10 @@ function logError(msg: string, config: Config) {
  * profiles.
  */
 export async function startLocal(config: Config = {}): Promise<void> {
-  const normalizedConfig = await initConfig(config);
-  profiler = new Profiler(normalizedConfig);
+  const profiler: Profiler|undefined = await createProfiler(config);
+  if (profiler === undefined) {
```
Comment (ofrobots) [inline ts/src/index.ts]: Likewise.

File: ts/test/test-heap-profiler.ts [hunk 24]
```diff
@@ -15,53 +15,116 @@
  */
 
 import * as delay from 'delay';
+import {describe} from 'mocha';
```
Comment (ofrobots) [inline ts/test/test-heap-profiler.ts]: Why was this needed? We were using `describe` before just fine. Note that we are not importing any of the other globals added by `mocha` (e.g. `beforeEach`).

File: ts/src/index.ts (hunk 19 above)
Comment (nolanmar511) [reply ts/src/index.ts]: We've never checked metadata for the service, so this would not be semver major.

File: ts/src/index.ts [hunk 25]
```diff
@@ -116,25 +123,21 @@ const profiler: Profiler|undefined = undefined;
...
+        ` does not satisfies "${pjson.engines.node}"`);
   }
 
   let profilerConfig: ProfilerConfig;
   try {
     profilerConfig = initConfigLocal(config);
   } catch (e) {
-    logError(`Could not start profiler: ${e}`, config);
-    return undefined;
+    throw new Error(`Could not start profiler: ${e}`);
```
Comment (ofrobots) [inline ts/src/index.ts]: It would be better to throw the original error. The additional message doesn't really add value. That is, I think you can omit the try/catch.

File: ts/src/index.ts [hunk 26]
```diff
@@ -72,6 +73,12 @@ function initConfigLocal(config: Config): ProfilerConfig {
   let envSetConfig: Config = {};
   const val = process.env.GCLOUD_PROFILER_CONFIG;
   if (val) {
+    try {
+      const envSetConfigBuf = fs.readFileSync(val);
+      envSetConfig = JSON.parse(envSetConfigBuf.toString());
```
Comment (ofrobots) [inline ts/src/index.ts]: It is good to keep your `try` block focussed. I think you are intending only to catch the the `JSON.parse()` error here. Reduce the `try` block to just that.

File: ts/src/index.ts [hunk 27]
```diff
@@ -116,25 +123,21 @@ const profiler: Profiler|undefined = undefined;
 
 /**
  * Initializes the config, and starts heap profiler if the heap profiler is
- * needed. Returns a profiler if creation is successful. Otherwise, returns
- * undefined.
+ * needed. Returns a profiler if creation is successful. Otherwise, throws an
+ * error.
```
Comment (ofrobots) [inline ts/src/index.ts]: The return value is actually a promise, so this function never throws actually. It will always be a promise – a rejected promise in the case of a throw.

File: ts/src/index.ts (hunk 20 above)
Comment (nolanmar511) [reply ts/src/index.ts]: Done

File: ts/src/index.ts (hunk 21 above)
Comment (nolanmar511) [reply ts/src/index.ts]: done

File: ts/src/index.ts (hunk 22 above)
Comment (nolanmar511) [reply ts/src/index.ts]: done

File: ts/src/index.ts (hunk 23 above)
Comment (nolanmar511) [reply ts/src/index.ts]: done

File: ts/test/test-heap-profiler.ts (hunk 24 above)
Comment (nolanmar511) [reply ts/test/test-heap-profiler.ts]: removed -- this isn't needed

File: ts/src/index.ts (hunk 25 above)
Comment (nolanmar511) [reply ts/src/index.ts]: Done.

File: ts/src/index.ts (hunk 26 above)
Comment (nolanmar511) [reply ts/src/index.ts]: Removed try/catch block.
I think it may make sense to just let the error be thrown.

File: ts/src/index.ts (hunk 27 above)
Comment (nolanmar511) [reply ts/src/index.ts]: changed comment.

**Comment by nolanmar511** [comment]
PTAL

File: ts/src/index.ts [hunk 28]
```diff
@@ -73,13 +73,28 @@ export async function initConfig(config: Config): Promise<ProfilerConfig> {
   let envSetConfig: Config = {};
   const val = process.env.GCLOUD_PROFILER_CONFIG;
   if (val) {
+    const envSetConfigBuf = fs.readFileSync(val);
```
Comment (aalexand) [inline ts/src/index.ts]: This will throw an exception if val points to a non-existing / non-readable file. Should this be handled?

File: ts/src/index.ts [hunk 29]
```diff
@@ -73,13 +73,28 @@ export async function initConfig(config: Config): Promise<ProfilerConfig> {
   let envSetConfig: Config = {};
   const val = process.env.GCLOUD_PROFILER_CONFIG;
```
Comment (aalexand) [inline ts/src/index.ts]: Rename val to "path"?

File: ts/src/profilers/heap-profiler.ts [hunk 30]
```diff
@@ -15,41 +15,52 @@
...
-
-  /**
-   * @param intervalBytes - average bytes between samples.
-   * @param stackDepth - upper limit on number of frames in stack for sample.
-   */
-  constructor(private intervalBytes: number, private stackDepth: number) {
-    this.enable();
-  }
+let enabled = false;
+let heapIntervalBytes = defaultConfig.heapIntervalBytes;
```
Comment (aalexand) [inline ts/src/profilers/heap-profiler.ts]: I think you could initialize heapIntervalBytes and heapStackDepth to zeros here. Any reason to depend on config?

File: ts/src/profilers/heap-profiler.ts [hunk 31]
```diff
@@ -15,41 +15,52 @@
...
+/*
+ * Collects a heap profile when heapProfiler is enabled. Otherwise throws
+ * an error.
+ */
+export function profile(): perftools.profiles.IProfile {
+  if (!enabled) {
+    throw new Error('Heap profiler is not enabled.');
   }
+  const result = profiler.getAllocationProfile();
+  const startTimeNanos = Date.now() * 1000 * 1000;
```
Comment (aalexand) [inline ts/src/profilers/heap-profiler.ts]: It would be slightly better to record the start time before calling getAllocationProfile maybe?

**Comment by aalexand** [comment]
@nolanmar511 Could you take a pass over the remaining minor comments?

File: ts/src/profilers/heap-profiler.ts (hunk 31 above)
Comment (nolanmar511) [reply ts/src/profilers/heap-profiler.ts]: done.

File: ts/src/profilers/heap-profiler.ts (hunk 30 above)
Comment (nolanmar511) [reply ts/src/profilers/heap-profiler.ts]: done.

**Comment by nolanmar511** [comment]
PTAL

File: ts/src/index.ts [hunk 32]
```diff
@@ -90,22 +113,41 @@ export async function initConfig(config: Config): Promise<ProfilerConfig> {
...
+export async function createProfiler(config: Config): Promise<Profiler> {
+  if (!semver.satisfies(process.version, pjson.engines.node)) {
+    throw new Error(
+        `Could not start profiler: node version ${process.version}` +
+        ` does not satisfies "${pjson.engines.node}"`);
   }
 
-  return mergedConfig;
-}
+  let profilerConfig: ProfilerConfig;
```
Comment (aalexand) [inline ts/src/index.ts]: This and next line could be single `let profilerConfig = initConfigLocal(config);` line?

Comment (nolanmar511) [reply ts/src/index.ts]: Done.

File: ts/test/test-init-config.ts [hunk 33]
```diff
@@ -137,12 +170,20 @@ describe('initConfig', () => {
          disableTime: false,
          projectId: 'fake-projectId',
        };
-       const initializedConfig = await initConfig(config);
+       const profiler: Profiler|undefined = await createProfiler(config);
+       if (profiler === undefined) {
+         assert.ok(true, 'profiler should be created successfully.');
```
Comment (ofrobots) [inline ts/test/test-init-config.ts]: The only case where `profiler` would be undefined is when `createProfiler` throws. What is this test trying to achieve?

This comment applies to all the places where this test is being done. Ideally, the type for the variable `profiler` should be `Profiler` rather than `Profiler|undefined`, but given that's the declared type of the function anyway, you should probably omit the type in the variable declaration here.

File: ts/test/test-init-config.ts [hunk 34]
```diff
@@ -70,7 +79,15 @@ describe('initConfig', () => {
...
-    const initializedConfig = await initConfig(config);
+    const profiler: Profiler|undefined = await createProfiler(config);
+    if (profiler === undefined) {
+      assert.ok(true, 'profiler should be created successfully.');
+      return;
+    }
+    const initializedConfig = profiler.config;
+    // remove interceptors_ field which is added to profiler.config.
+    // tslint:disable-next-line: no-any
+    delete (initializedConfig as any).interceptors_;
```
Comment (ofrobots) [inline ts/test/test-init-config.ts]: It might better to call `common.util.normalizeConfig` on `internalConfigParams` above and avoid this complexity here in each of the tests.

Comment (nolanmar511) [reply ts/test/test-init-config.ts]: Done.

File: ts/test/test-init-config.ts (hunk 33 above)
Comment (nolanmar511) [reply ts/test/test-init-config.ts]: Done.

**Comment by nolanmar511** [comment]
PTAL

File: ts/test/test-init-config.ts [hunk 35]
```diff
@@ -70,8 +82,10 @@ describe('initConfig', () => {
       zone: 'zone',
       projectId: 'fake-projectId'
     };
-    const initializedConfig = await initConfig(config);
-    assert.deepEqual(initializedConfig, extend(config, internalConfigParams));
+    const profiler: Profiler = await createProfiler(config);
+    const expConfig = await common.util.normalizeArguments(
```
Comment (ofrobots) [inline ts/test/test-init-config.ts]: suggestion: would it be possible to move `normalizeArugments` call to an outer scope, and use the following here:
```ts
const expConfig = extend({},DEFAULT_CONFIG, config);
```

where `DEFAULT_CONFIG` could be:
```ts
const DEFAULT_CONFIG = await common.util.normalizeArguments(null, internalConfigParams);
Object.freeze(DEFAULT_CONFIG);
```

Comment (nolanmar511) [reply ts/test/test-init-config.ts]: It doesn't seem to be possible. 
I don't know why, but when I do this, I get a lot of:
```
     TypeError: Attempted to wrap instance which is already wrapped
```

Comment (nolanmar511) [reply ts/test/test-init-config.ts]: [patch.patch.zip](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/files/1962425/patch.patch.zip)

Comment (ofrobots) [reply ts/test/test-init-config.ts]: I think the reason it doesn't work is because mocha probably doesn't support `describe` blocks to be async.

I would suggest a patch along the lines of:

```diff
diff --git a/ts/test/test-init-config.ts b/ts/test/test-init-config.ts
index 4082ad588..27af2c09d 100644
--- a/ts/test/test-init-config.ts
+++ b/ts/test/test-init-config.ts
@@ -33,7 +33,23 @@ describe('createProfiler', async () => {
   let metadataStub: sinon.SinonStub|undefined;
   let startStub: sinon.SinonStub;
 
-  before(() => {
+  const internalConfigParams = {
+    timeIntervalMicros: 1000,
+    heapIntervalBytes: 512 * 1024,
+    heapMaxStackDepth: 64,
+    initialBackoffMillis: 1000 * 60,
+    backoffCapMillis: 60 * 60 * 1000,
+    backoffMultiplier: 1.3,
+    serverBackoffCapMillis: 2147483647,
+    localProfilingPeriodMillis: 1000,
+    localTimeDurationMillis: 1000,
+    localLogPeriodMillis: 10000,
+    baseApiUrl: 'https://cloudprofiler.googleapis.com/v2',
+  };
+  let defaultConfig : typeof internalConfigParams;
+
+  before(async () => {
+    defaultConfig = await common.util.normalizeArguments(null, extend({}, internalConfigParams));
     startStub = sinon.stub(v8HeapProfiler, 'startSamplingHeapProfiler');
     savedEnv = process.env;
   });
@@ -55,19 +71,8 @@ describe('createProfiler', async () => {
     startStub.restore();
   });
 
-  const internalConfigParams = {
-    timeIntervalMicros: 1000,
-    heapIntervalBytes: 512 * 1024,
-    heapMaxStackDepth: 64,
-    initialBackoffMillis: 1000 * 60,
-    backoffCapMillis: 60 * 60 * 1000,
-    backoffMultiplier: 1.3,
-    serverBackoffCapMillis: 2147483647,
-    localProfilingPeriodMillis: 1000,
-    localTimeDurationMillis: 1000,
-    localLogPeriodMillis: 10000,
-    baseApiUrl: 'https://cloudprofiler.googleapis.com/v2',
-  };
+
+
 
   it('should not modify specified fields when not on GCE', async () => {
     metadataStub = sinon.stub(gcpMetadata, 'instance')
@@ -83,8 +88,9 @@ describe('createProfiler', async () => {
       projectId: 'fake-projectId'
     };
     const profiler: Profiler = await createProfiler(config);
-    const expConfig = await common.util.normalizeArguments(
-        null, extend({}, internalConfigParams, config));
+    // const expConfig = await common.util.normalizeArguments(
+    //     null, extend({}, internalConfigParams, config));
+    const expConfig = Object.assign({}, defaultConfig, config);
     assert.deepEqual(profiler.config, expConfig);
   });
 

```

Comment (nolanmar511) [reply ts/test/test-init-config.ts]: Done.

**Comment by nolanmar511** [comment]
PTAL
