### PR TITLE
fix: fix ESOCKETTIMEDOUT Error by increasing timeout to 1 hour for createProfile()

### LINKED ISSUE #70: Sporadic ESOCKETTIMEDOUT error during profiling
I am running the following program on GCE:
```
require('@google-cloud/profiler').start({
    serviceContext: {
    service: 'test-service',
    version: '1.0.0',
    logLevel: 4,
  },
});

var doSomeWork = () => {
  console.log("doing some work");
  for (var i = 0; i < 1e8; i++) {
  }
};

setInterval(doSomeWork, 1000);
```

Once in a while I am getting an error like:
```
...
doing some work
doing some work
ERROR:@google-cloud/profiler: Error requesting profile type to be collected: Error: ESOCKETTIMEDOUT.
doing some work
doing some work
...
```

There may be some unexpected timeout happening on the profile creation.

### PR DESCRIPTION
**Pull request by nolanmar511**
Fixes #70 

I tested by running 8 copies of the acmeAir app both before and after this change (for about 10 minutes). Before, ESOCKETTIMEDOUT errors occurred on every request to createProfile(), after, no ESOCKETTIMEDOUT errors were observed.

### CODE REVIEW

File: ts/src/profiler.ts [hunk 1]
```diff
@@ -267,6 +267,7 @@ export class Profiler extends common.ServiceObject {
       uri: '/profiles',
       body: reqBody,
       json: true,
+      timeout: 60 * 60 * 1000,
```
Comment (aalexand) [inline ts/src/profiler.ts]: It would deserve a comment about why the timeout is overridden from the default.

Comment (aalexand) [inline ts/src/profiler.ts]: You don't have new tests in the PR, so presumably some manual testing was done to verify the fix. Can you describe the testing you did in the PR description?

Comment (nolanmar511) [reply ts/src/profiler.ts]: done.

Comment (nolanmar511) [reply ts/src/profiler.ts]: Done.

File: ts/src/profiler.ts [hunk 2]
```diff
@@ -267,6 +267,11 @@ export class Profiler extends common.ServiceObject {
       uri: '/profiles',
       body: reqBody,
       json: true,
+
+      // Default timeout for for request is 1 minute, but request to create
+      // profile is designed to hang until it is time to collect a profile
+      // (up to one hour).
+      timeout: 60 * 60 * 1000,
```
Comment (aalexand) [inline ts/src/profiler.ts]: Also: I thought we started to use parseDuration('1h')-like expressions instead of doing the direct math with millis?

Comment (nolanmar511) [reply ts/src/profiler.ts]: Yes -- Done.

**Comment by gaofanmichael** [comment]
Looks like if you delete empty line 270 in ts/test/test-profiler.ts, gts will be happy.

**Comment by nolanmar511** [comment]
Tests working now -- PTAL

**Comment by ofrobots** [comment]
Please use https://conventionalcommits.org/ style for commit messages.
