### PR TITLE
fix: add modules needed to compile the profiler in typescript

### LINKED ISSUE #171: Integration test for typescript application should be added
#169 shows that our agent can have typescript-specific problems. So, we should update the e2e tests to test the workflow with a typescript application.

### LINKED ISSUE #304: Cannot compile a typescript application with latest release of profiler.
When I try to compile a typescript module with the profiler added, I get this error:
```
node_modules/@google-cloud/profiler/out/src/index.d.ts:16:34 - error TS7016: Could not find a declaration file for module 'console-log-level'. '/usr/local/google/home/nolanmar/ts-test/test-ts/node_modules/console-log-level/index.js' implicitly has an 'any' type.
  Try `npm install @types/console-log-level` if it exists or add a new declaration (.d.ts) file containing `declare module 'console-log-level';`

16 import * as consoleLogLevel from 'console-log-level';
                                    ~~~~~~~~~~~~~~~~~~~

node_modules/@google-cloud/profiler/out/src/index.d.ts:17:24 - error TS7016: Could not find a declaration file for module 'semver'. '/usr/local/google/home/nolanmar/ts-test/test-ts/node_modules/semver/semver.js' implicitly has an 'any' type.
  Try `npm install @types/semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'semver';`

17 import { SemVer } from 'semver';
                          ~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-ts@1.0.0 compile: `tsc -p .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-ts@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/google/home/nolanmar/.npm/_logs/2018-09-28T16_55_15_799Z-debug.log
```

### PR DESCRIPTION
**Pull request by nolanmar511**
Fixes #304, fixes #171

### CODE REVIEW

File: testing/integration_test.go [hunk 1]
```diff
@@ -92,13 +92,15 @@ PROFILER="$HOME/cloud-profiler-nodejs/google-cloud-profiler-$VERSION.tgz"
 
 TESTDIR="$HOME/test"
 mkdir -p "$TESTDIR"
-cp "testing/busybench.js" "$TESTDIR"
-cd "$TESTDIR"
+cp -r "testing/ts-bench" "$TESTDIR"
```
Comment (aalexand) [inline testing/integration_test.go]: Nit: could we call the directory just "busybench"? The "ts-" prefix is not that important.

Comment (nolanmar511) [reply testing/integration_test.go]: Done.

**Comment by aalexand** [comment]
FWIW, see https://help.github.com/articles/closing-issues-using-keywords/#closing-multiple-issues, to mark PR as fixing multiple issues the keyword needs to be used before each issue ID. I'll fix that.
